### PR TITLE
Async port - draft

### PR DESCRIPTION
**Pull request by davidgraeff**
Missing:
* Examples need to be ported
* Blocking methods for the session type are missing
* Formatting

### CODE REVIEW

**Comment by mardab** [comment]
What about adding wasm support as well? I tried building with this branch, and the only problem seems to be `mio`, which does not support wasm yet.

**Comment by davidgraeff** [comment]
Wasm is not on my personal target list, but as soon as all dependencies (tokio, reqwest, oauth) support wasm this crate will do so as well :)

**Comment by mardab** [comment]
Thanks, that would be nice, manually working with firestore/firebase is a lot of trouble.

**Comment by davidgraeff** [comment]
It's trickier than you think to provide an async and sync API without too much code duplication and without the async version to allocate. I'm haven't figured out all pieces yet.

**Comment by davidgraeff** [comment]
Async support has been merged with PR https://github.com/davidgraeff/firestore-db-and-auth-rs/pull/34

**Pull request closed without merging**
